Backup failed for Site doodle.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f12e90058a0>
      exit_code = 0
      rollback_callback = None
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f12e7f45c60>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f12e7f45c60>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f12e7f45d00>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f12e7f45c60>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f12e7f45d00>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7f2f590>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f12e7fc4bf0>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f12e7f3d8a0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f12e7f3d940>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7f2f590>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7f2f590>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7f2f590>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7f2f590>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7f2f590>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f12e7f2d730>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f12e8051260>, <class 'int'>: <function escape_int at 0x7f12e8051300>, <class 'float'>: <function escape_float at 0x7f12e80513a0>, <class 'str'>: <function escape_str at 0x7f12e8051620>, <class 'bytes'>: <function escape_bytes at 0x7f12e8051580>, <class 'tuple'>: <function escape_sequence at 0x7f12e8051120>, <class 'list'>: <function escape_sequence at 0x7f12e8051120>, <class 'set'>: <function escape_sequence at 0x7f12e8051120>, <class 'frozenset'>: <function escape_sequence at 0x7f12e8051120>, <class 'dict'>: <function escape_dict at 0x7f12e8051080>, <class 'NoneType'>: <function escape_None at 0x7f12e80516c0>, <class 'datetime.date'>: <function escape_date at 0x7f12e8051940>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f12e80518a0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f12e8051760>, <class 'datetime.time'>: <function escape_time at 0x7f12e8051800>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f12e7f2d730>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f12e7f2d730>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14\xdd\xf55\xd8Fz\xa1\xcb\xf6\xc0|\xec \xcb\xa1\xdf\x86\x95}\xdc_c50e25a1751d5327\x00mysql_native_password\x005\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x045891'
      authresp = b'\xdd\xf55\xd8Fz\xa1\xcb\xf6\xc0|\xec \xcb\xa1\xdf\x86\x95}\xdc'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x045891'
      k = b'_pid'
      v = b'5891'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f12e7f2d730>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f12e7f45f00>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f12e7f45f00>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test2. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f12e90058a0>
      exit_code = 1
      rollback_callback = None
      site = 'doodle.test2'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f12e7f45c30>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f12e7f45c30>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f12e7f45a90>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f12e7f45c30>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f12e7f45a90>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7fc4bf0>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f12e7f45ee0>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f12e7f3d8a0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f12e7f3d940>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7fc4bf0>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7fc4bf0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7fc4bf0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7fc4bf0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f12e7fc4bf0>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f12e7f45d30>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f12e8051260>, <class 'int'>: <function escape_int at 0x7f12e8051300>, <class 'float'>: <function escape_float at 0x7f12e80513a0>, <class 'str'>: <function escape_str at 0x7f12e8051620>, <class 'bytes'>: <function escape_bytes at 0x7f12e8051580>, <class 'tuple'>: <function escape_sequence at 0x7f12e8051120>, <class 'list'>: <function escape_sequence at 0x7f12e8051120>, <class 'set'>: <function escape_sequence at 0x7f12e8051120>, <class 'frozenset'>: <function escape_sequence at 0x7f12e8051120>, <class 'dict'>: <function escape_dict at 0x7f12e8051080>, <class 'NoneType'>: <function escape_None at 0x7f12e80516c0>, <class 'datetime.date'>: <function escape_date at 0x7f12e8051940>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f12e80518a0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f12e8051760>, <class 'datetime.time'>: <function escape_time at 0x7f12e8051800>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f12e7f45d30>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f12e7f45d30>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14\xbaJ\x86ZS\xa3H\xdem\xbb\x0e\xe3G|B\xf9\xe3L\x99H_c50e25a1751d5327\x00mysql_native_password\x005\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x045891'
      authresp = b'\xbaJ\x86ZS\xa3H\xdem\xbb\x0e\xe3G|B\xf9\xe3L\x99H'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x045891'
      k = b'_pid'
      v = b'5891'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f12e7f45d30>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f12e7f2d870>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f12e7f2d870>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f2a497c98a0>
      exit_code = 0
      rollback_callback = None
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f2a486d5e70>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f2a486d5e70>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f2a487c0350>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f2a486d5e70>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f2a487c0350>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a486bb770>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f2a49d25c10>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f2a486cd8a0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f2a486cd940>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a486bb770>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a486bb770>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a486bb770>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a486bb770>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a486bb770>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f2a49ba0bf0>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f2a48821260>, <class 'int'>: <function escape_int at 0x7f2a48821300>, <class 'float'>: <function escape_float at 0x7f2a488213a0>, <class 'str'>: <function escape_str at 0x7f2a48821620>, <class 'bytes'>: <function escape_bytes at 0x7f2a48821580>, <class 'tuple'>: <function escape_sequence at 0x7f2a48821120>, <class 'list'>: <function escape_sequence at 0x7f2a48821120>, <class 'set'>: <function escape_sequence at 0x7f2a48821120>, <class 'frozenset'>: <function escape_sequence at 0x7f2a48821120>, <class 'dict'>: <function escape_dict at 0x7f2a48821080>, <class 'NoneType'>: <function escape_None at 0x7f2a488216c0>, <class 'datetime.date'>: <function escape_date at 0x7f2a48821940>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f2a488218a0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f2a48821760>, <class 'datetime.time'>: <function escape_time at 0x7f2a48821800>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f2a49ba0bf0>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f2a49ba0bf0>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14\x85#\x1d\x14\xa3\xfdx\xa8U\x07\xf3\xd4\x9e\x05\xb4D\x08H\xef\xa5_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0529641'
      authresp = b'\x85#\x1d\x14\xa3\xfdx\xa8U\x07\xf3\xd4\x9e\x05\xb4D\x08H\xef\xa5'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0529641'
      k = b'_pid'
      v = b'29641'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f2a49ba0bf0>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f2a486d5ff0>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f2a486d5ff0>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test2. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f2a497c98a0>
      exit_code = 1
      rollback_callback = None
      site = 'doodle.test2'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f2a486bb760>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f2a486bb760>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f2a4ac005f0>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f2a486bb760>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f2a4ac005f0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a487c0350>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f2a486d5e80>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f2a486cd8a0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f2a486cd940>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a487c0350>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a487c0350>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a487c0350>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a487c0350>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f2a487c0350>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f2a486d5fd0>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f2a48821260>, <class 'int'>: <function escape_int at 0x7f2a48821300>, <class 'float'>: <function escape_float at 0x7f2a488213a0>, <class 'str'>: <function escape_str at 0x7f2a48821620>, <class 'bytes'>: <function escape_bytes at 0x7f2a48821580>, <class 'tuple'>: <function escape_sequence at 0x7f2a48821120>, <class 'list'>: <function escape_sequence at 0x7f2a48821120>, <class 'set'>: <function escape_sequence at 0x7f2a48821120>, <class 'frozenset'>: <function escape_sequence at 0x7f2a48821120>, <class 'dict'>: <function escape_dict at 0x7f2a48821080>, <class 'NoneType'>: <function escape_None at 0x7f2a488216c0>, <class 'datetime.date'>: <function escape_date at 0x7f2a48821940>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f2a488218a0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f2a48821760>, <class 'datetime.time'>: <function escape_time at 0x7f2a48821800>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f2a486d5fd0>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f2a486d5fd0>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14\xccb\xc3\xcb\xa4\x99\xbc\xd4\x13!\xbc\xa4\x80S\xd1\xa0\x94\x95d\x9d_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0529641'
      authresp = b'\xccb\xc3\xcb\xa4\x99\xbc\xd4\x13!\xbc\xa4\x80S\xd1\xa0\x94\x95d\x9d'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0529641'
      k = b'_pid'
      v = b'29641'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f2a486d5fd0>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f2a497a4d00>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f2a497a4d00>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f651a29dda0>
      exit_code = 0
      rollback_callback = None
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f65191b7460>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f65191b7460>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f65191b7500>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f65191b7460>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f65191b7500>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f65191b4e00>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f6519262ae0>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f65191b1da0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f65191b1e40>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f65191b4e00>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f65191b4e00>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f65191b4e00>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f65191b4e00>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f65191b4e00>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f65192633b0>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f6519309760>, <class 'int'>: <function escape_int at 0x7f6519309800>, <class 'float'>: <function escape_float at 0x7f65193098a0>, <class 'str'>: <function escape_str at 0x7f6519309b20>, <class 'bytes'>: <function escape_bytes at 0x7f6519309a80>, <class 'tuple'>: <function escape_sequence at 0x7f6519309620>, <class 'list'>: <function escape_sequence at 0x7f6519309620>, <class 'set'>: <function escape_sequence at 0x7f6519309620>, <class 'frozenset'>: <function escape_sequence at 0x7f6519309620>, <class 'dict'>: <function escape_dict at 0x7f6519309580>, <class 'NoneType'>: <function escape_None at 0x7f6519309bc0>, <class 'datetime.date'>: <function escape_date at 0x7f6519309e40>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f6519309da0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f6519309c60>, <class 'datetime.time'>: <function escape_time at 0x7f6519309d00>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f65192633b0>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f65192633b0>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14\x93\x17\x8f\x8a\xec\x83"\xd0? \xa3e\xc3\xce\xe1#7\xb39e_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0548143'
      authresp = b'\x93\x17\x8f\x8a\xec\x83"\xd0? \xa3e\xc3\xce\xe1#7\xb39e'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0548143'
      k = b'_pid'
      v = b'48143'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f65192633b0>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f65191b76a0>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f65191b76a0>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test2. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f651a29dda0>
      exit_code = 1
      rollback_callback = None
      site = 'doodle.test2'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f651b1a5c30>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f651b1a5c30>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f65191b7410>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f651b1a5c30>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f65191b7410>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f651a649dc0>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f65191b7500>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f65191b1da0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f65191b1e40>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f651a649dc0>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f651a649dc0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f651a649dc0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f651a649dc0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f651a649dc0>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f65191b75c0>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f6519309760>, <class 'int'>: <function escape_int at 0x7f6519309800>, <class 'float'>: <function escape_float at 0x7f65193098a0>, <class 'str'>: <function escape_str at 0x7f6519309b20>, <class 'bytes'>: <function escape_bytes at 0x7f6519309a80>, <class 'tuple'>: <function escape_sequence at 0x7f6519309620>, <class 'list'>: <function escape_sequence at 0x7f6519309620>, <class 'set'>: <function escape_sequence at 0x7f6519309620>, <class 'frozenset'>: <function escape_sequence at 0x7f6519309620>, <class 'dict'>: <function escape_dict at 0x7f6519309580>, <class 'NoneType'>: <function escape_None at 0x7f6519309bc0>, <class 'datetime.date'>: <function escape_date at 0x7f6519309e40>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f6519309da0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f6519309c60>, <class 'datetime.time'>: <function escape_time at 0x7f6519309d00>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f65191b75c0>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f65191b75c0>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14<\xfd4\xb9\xe3\xe4q\n\xcb\xe8s-\x80^l\x7f\xd6\xfc\xd2:_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0548143'
      authresp = b'<\xfd4\xb9\xe3\xe4q\n\xcb\xe8s-\x80^l\x7f\xd6\xfc\xd2:'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0548143'
      k = b'_pid'
      v = b'48143'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f65191b75c0>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f651a2cdea0>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f651a2cdea0>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f536d4885e0>
      exit_code = 0
      rollback_callback = None
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f536c39de70>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f536c39de70>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f536c39df10>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f536c39de70>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f536c39df10>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536c440a10>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f536c39dfd0>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f536c3885e0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f536c388680>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536c440a10>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536c440a10>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536c440a10>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536c440a10>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536c440a10>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f536de92cf0>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f536c49bf60>, <class 'int'>: <function escape_int at 0x7f536c4a4040>, <class 'float'>: <function escape_float at 0x7f536c4a40e0>, <class 'str'>: <function escape_str at 0x7f536c4a4360>, <class 'bytes'>: <function escape_bytes at 0x7f536c4a42c0>, <class 'tuple'>: <function escape_sequence at 0x7f536c49be20>, <class 'list'>: <function escape_sequence at 0x7f536c49be20>, <class 'set'>: <function escape_sequence at 0x7f536c49be20>, <class 'frozenset'>: <function escape_sequence at 0x7f536c49be20>, <class 'dict'>: <function escape_dict at 0x7f536c49bd80>, <class 'NoneType'>: <function escape_None at 0x7f536c4a4400>, <class 'datetime.date'>: <function escape_date at 0x7f536c4a4680>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f536c4a45e0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f536c4a44a0>, <class 'datetime.time'>: <function escape_time at 0x7f536c4a4540>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f536de92cf0>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f536de92cf0>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14\xdaI\x9c=\x93\x90\x10\x1dK\x82\x16\x18\x18H\xab\x83\xd5\xb7\xa06_c50e25a1751d5327\x00mysql_native_password\x005\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x048469'
      authresp = b'\xdaI\x9c=\x93\x90\x10\x1dK\x82\x16\x18\x18H\xab\x83\xd5\xb7\xa06'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x048469'
      k = b'_pid'
      v = b'8469'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f536de92cf0>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f536c39e170>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f536c39e170>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test2. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f536d4885e0>
      exit_code = 1
      rollback_callback = None
      site = 'doodle.test2'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f536c440a00>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f536c440a00>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f536c37bb90>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f536c440a00>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f536c37bb90>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536d496390>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f536c39e090>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f536c3885e0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f536c388680>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536d496390>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536d496390>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536d496390>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536d496390>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f536d496390>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f536c39df40>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f536c49bf60>, <class 'int'>: <function escape_int at 0x7f536c4a4040>, <class 'float'>: <function escape_float at 0x7f536c4a40e0>, <class 'str'>: <function escape_str at 0x7f536c4a4360>, <class 'bytes'>: <function escape_bytes at 0x7f536c4a42c0>, <class 'tuple'>: <function escape_sequence at 0x7f536c49be20>, <class 'list'>: <function escape_sequence at 0x7f536c49be20>, <class 'set'>: <function escape_sequence at 0x7f536c49be20>, <class 'frozenset'>: <function escape_sequence at 0x7f536c49be20>, <class 'dict'>: <function escape_dict at 0x7f536c49bd80>, <class 'NoneType'>: <function escape_None at 0x7f536c4a4400>, <class 'datetime.date'>: <function escape_date at 0x7f536c4a4680>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f536c4a45e0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f536c4a44a0>, <class 'datetime.time'>: <function escape_time at 0x7f536c4a4540>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f536c39df40>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f536c39df40>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14\x9a\xbcg\xabq\xde\x87\xb7~\xf6X\xd1T\x0fm\xa04\xda\xfe7_c50e25a1751d5327\x00mysql_native_password\x005\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x048469'
      authresp = b'\x9a\xbcg\xabq\xde\x87\xb7~\xf6X\xd1T\x0fm\xa04\xda\xfe7'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x048469'
      k = b'_pid'
      v = b'8469'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f536c39df40>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f536d403cd0>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f536d403cd0>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f578b3ac5e0>
      exit_code = 0
      rollback_callback = None
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f578a2f2080>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f578a2f2080>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f578a2f2120>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f578a2f2080>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f578a2f2120>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578a2d3800>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f578a2f2240>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f578a2e45e0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f578a2e4680>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578a2d3800>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578a2d3800>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578a2d3800>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578a2d3800>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578a2d3800>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f578c5a5790>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f578a42ff60>, <class 'int'>: <function escape_int at 0x7f578a43c040>, <class 'float'>: <function escape_float at 0x7f578a43c0e0>, <class 'str'>: <function escape_str at 0x7f578a43c360>, <class 'bytes'>: <function escape_bytes at 0x7f578a43c2c0>, <class 'tuple'>: <function escape_sequence at 0x7f578a42fe20>, <class 'list'>: <function escape_sequence at 0x7f578a42fe20>, <class 'set'>: <function escape_sequence at 0x7f578a42fe20>, <class 'frozenset'>: <function escape_sequence at 0x7f578a42fe20>, <class 'dict'>: <function escape_dict at 0x7f578a42fd80>, <class 'NoneType'>: <function escape_None at 0x7f578a43c400>, <class 'datetime.date'>: <function escape_date at 0x7f578a43c680>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f578a43c5e0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f578a43c4a0>, <class 'datetime.time'>: <function escape_time at 0x7f578a43c540>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f578c5a5790>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f578c5a5790>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b"\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14b\xb7d\xa6\x10\xc6\xd3I\xf3\xb48\xfa:\xcc\x0c\x93\r'\xc1F_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0521041"
      authresp = b"b\xb7d\xa6\x10\xc6\xd3I\xf3\xb48\xfa:\xcc\x0c\x93\r'\xc1F"
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0521041'
      k = b'_pid'
      v = b'21041'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f578c5a5790>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f578a2f2200>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f578a2f2200>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test2. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f578b3ac5e0>
      exit_code = 1
      rollback_callback = None
      site = 'doodle.test2'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f578b385570>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f578b385570>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f578a2f2210>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f578b385570>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f578a2f2210>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578b3e6030>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f578bbea6c0>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f578a2e45e0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f578a2e4680>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578b3e6030>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578b3e6030>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578b3e6030>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578b3e6030>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f578b3e6030>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f578a1905f0>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f578a42ff60>, <class 'int'>: <function escape_int at 0x7f578a43c040>, <class 'float'>: <function escape_float at 0x7f578a43c0e0>, <class 'str'>: <function escape_str at 0x7f578a43c360>, <class 'bytes'>: <function escape_bytes at 0x7f578a43c2c0>, <class 'tuple'>: <function escape_sequence at 0x7f578a42fe20>, <class 'list'>: <function escape_sequence at 0x7f578a42fe20>, <class 'set'>: <function escape_sequence at 0x7f578a42fe20>, <class 'frozenset'>: <function escape_sequence at 0x7f578a42fe20>, <class 'dict'>: <function escape_dict at 0x7f578a42fd80>, <class 'NoneType'>: <function escape_None at 0x7f578a43c400>, <class 'datetime.date'>: <function escape_date at 0x7f578a43c680>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f578a43c5e0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f578a43c4a0>, <class 'datetime.time'>: <function escape_time at 0x7f578a43c540>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f578a1905f0>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f578a1905f0>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14|H\xb2\x00+\xa8\r\x82]\xe4\x81\xf4\x98\x02\xa4\x13\xe8\xdaf\x16_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0521041'
      authresp = b'|H\xb2\x00+\xa8\r\x82]\xe4\x81\xf4\x98\x02\xa4\x13\xe8\xdaf\x16'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0521041'
      k = b'_pid'
      v = b'21041'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f578a1905f0>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f578a190610>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f578a190610>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f9a6249c5e0>
      exit_code = 0
      rollback_callback = None
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f9a613b5de0>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f9a613b5de0>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f9a613b5e80>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f9a613b5de0>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f9a613b5e80>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a61397590>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f9a612fb6e0>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f9a6139c5e0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f9a6139c680>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a61397590>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a61397590>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a61397590>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a61397590>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a61397590>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f9a624752b0>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f9a614eff60>, <class 'int'>: <function escape_int at 0x7f9a614fc040>, <class 'float'>: <function escape_float at 0x7f9a614fc0e0>, <class 'str'>: <function escape_str at 0x7f9a614fc360>, <class 'bytes'>: <function escape_bytes at 0x7f9a614fc2c0>, <class 'tuple'>: <function escape_sequence at 0x7f9a614efe20>, <class 'list'>: <function escape_sequence at 0x7f9a614efe20>, <class 'set'>: <function escape_sequence at 0x7f9a614efe20>, <class 'frozenset'>: <function escape_sequence at 0x7f9a614efe20>, <class 'dict'>: <function escape_dict at 0x7f9a614efd80>, <class 'NoneType'>: <function escape_None at 0x7f9a614fc400>, <class 'datetime.date'>: <function escape_date at 0x7f9a614fc680>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f9a614fc5e0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f9a614fc4a0>, <class 'datetime.time'>: <function escape_time at 0x7f9a614fc540>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f9a624752b0>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f9a624752b0>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14\x8bP\x02\xce\xd1xn+\r\xfc\xa3*b\x8f\x9b:\xad\xa2\x93\xb5_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0520485'
      authresp = b'\x8bP\x02\xce\xd1xn+\r\xfc\xa3*b\x8f\x9b:\xad\xa2\x93\xb5'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0520485'
      k = b'_pid'
      v = b'20485'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f9a624752b0>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f9a613b6020>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f9a613b6020>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test2. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f9a6249c5e0>
      exit_code = 1
      rollback_callback = None
      site = 'doodle.test2'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f9a614fa1a0>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f9a614fa1a0>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f9a613b6000>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f9a614fa1a0>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f9a613b6000>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a62e28bf0>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f9a61248350>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f9a6139c5e0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f9a6139c680>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a62e28bf0>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a62e28bf0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a62e28bf0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a62e28bf0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f9a62e28bf0>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f9a612483b0>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f9a614eff60>, <class 'int'>: <function escape_int at 0x7f9a614fc040>, <class 'float'>: <function escape_float at 0x7f9a614fc0e0>, <class 'str'>: <function escape_str at 0x7f9a614fc360>, <class 'bytes'>: <function escape_bytes at 0x7f9a614fc2c0>, <class 'tuple'>: <function escape_sequence at 0x7f9a614efe20>, <class 'list'>: <function escape_sequence at 0x7f9a614efe20>, <class 'set'>: <function escape_sequence at 0x7f9a614efe20>, <class 'frozenset'>: <function escape_sequence at 0x7f9a614efe20>, <class 'dict'>: <function escape_dict at 0x7f9a614efd80>, <class 'NoneType'>: <function escape_None at 0x7f9a614fc400>, <class 'datetime.date'>: <function escape_date at 0x7f9a614fc680>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f9a614fc5e0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f9a614fc4a0>, <class 'datetime.time'>: <function escape_time at 0x7f9a614fc540>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f9a612483b0>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f9a612483b0>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14\xbb\xdb\x12\x96?\x1e\xc2\t\x06\xe0H5v\x87\x8f<\xa1\x8e\x96\x9a_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0520485'
      authresp = b'\xbb\xdb\x12\x96?\x1e\xc2\t\x06\xe0H5v\x87\x8f<\xa1\x8e\x96\x9a'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0520485'
      k = b'_pid'
      v = b'20485'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f9a612483b0>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f9a612483d0>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f9a612483d0>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f37069ac5e0>
      exit_code = 0
      rollback_callback = None
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f37058c2050>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f37058c2050>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f37058c20f0>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f37058c2050>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f37058c20f0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3705a07e00>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f3705887800>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f37058a85e0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f37058a8680>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3705a07e00>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3705a07e00>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3705a07e00>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3705a07e00>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3705a07e00>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f3706ba36e0>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f37059fff60>, <class 'int'>: <function escape_int at 0x7f3705a0c040>, <class 'float'>: <function escape_float at 0x7f3705a0c0e0>, <class 'str'>: <function escape_str at 0x7f3705a0c360>, <class 'bytes'>: <function escape_bytes at 0x7f3705a0c2c0>, <class 'tuple'>: <function escape_sequence at 0x7f37059ffe20>, <class 'list'>: <function escape_sequence at 0x7f37059ffe20>, <class 'set'>: <function escape_sequence at 0x7f37059ffe20>, <class 'frozenset'>: <function escape_sequence at 0x7f37059ffe20>, <class 'dict'>: <function escape_dict at 0x7f37059ffd80>, <class 'NoneType'>: <function escape_None at 0x7f3705a0c400>, <class 'datetime.date'>: <function escape_date at 0x7f3705a0c680>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f3705a0c5e0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f3705a0c4a0>, <class 'datetime.time'>: <function escape_time at 0x7f3705a0c540>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f3706ba36e0>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f3706ba36e0>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14\x13V\xc2\x8e=\xfb\x8f\x19\x85#\xa6\x95EL\xab\x01?ZP\x88_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0578613'
      authresp = b'\x13V\xc2\x8e=\xfb\x8f\x19\x85#\xa6\x95EL\xab\x01?ZP\x88'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0578613'
      k = b'_pid'
      v = b'78613'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f3706ba36e0>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f37058a19c0>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f37058a19c0>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test2. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f37069ac5e0>
      exit_code = 1
      rollback_callback = None
      site = 'doodle.test2'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f37097ad570>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f37097ad570>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f37058a19d0>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f37097ad570>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f37058a19d0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3706c4acf0>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f37056f22d0>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f37058a85e0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f37058a8680>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3706c4acf0>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3706c4acf0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3706c4acf0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3706c4acf0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f3706c4acf0>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f37058c2900>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f37059fff60>, <class 'int'>: <function escape_int at 0x7f3705a0c040>, <class 'float'>: <function escape_float at 0x7f3705a0c0e0>, <class 'str'>: <function escape_str at 0x7f3705a0c360>, <class 'bytes'>: <function escape_bytes at 0x7f3705a0c2c0>, <class 'tuple'>: <function escape_sequence at 0x7f37059ffe20>, <class 'list'>: <function escape_sequence at 0x7f37059ffe20>, <class 'set'>: <function escape_sequence at 0x7f37059ffe20>, <class 'frozenset'>: <function escape_sequence at 0x7f37059ffe20>, <class 'dict'>: <function escape_dict at 0x7f37059ffd80>, <class 'NoneType'>: <function escape_None at 0x7f3705a0c400>, <class 'datetime.date'>: <function escape_date at 0x7f3705a0c680>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f3705a0c5e0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f3705a0c4a0>, <class 'datetime.time'>: <function escape_time at 0x7f3705a0c540>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f37058c2900>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f37058c2900>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14\xa1\x89\x80\xaf\xa5\xe3\xac\x90\xf2\xc4\x16\xe14\x91\x15\x99k\xf4ho_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0578613'
      authresp = b'\xa1\x89\x80\xaf\xa5\xe3\xac\x90\xf2\xc4\x16\xe14\x91\x15\x99k\xf4ho'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0578613'
      k = b'_pid'
      v = b'78613'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f37058c2900>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f3705754400>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f3705754400>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f84b0c4c5e0>
      exit_code = 0
      rollback_callback = None
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f84afb61c00>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f84afb61c00>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f84afb43b60>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f84afb61c00>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f84afb43b60>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84afc07920>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f84afb61dc0>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f84afb485e0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f84afb48680>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84afc07920>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84afc07920>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84afc07920>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84afc07920>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84afc07920>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f84b1550ef0>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f84afc5bf60>, <class 'int'>: <function escape_int at 0x7f84afc68040>, <class 'float'>: <function escape_float at 0x7f84afc680e0>, <class 'str'>: <function escape_str at 0x7f84afc68360>, <class 'bytes'>: <function escape_bytes at 0x7f84afc682c0>, <class 'tuple'>: <function escape_sequence at 0x7f84afc5be20>, <class 'list'>: <function escape_sequence at 0x7f84afc5be20>, <class 'set'>: <function escape_sequence at 0x7f84afc5be20>, <class 'frozenset'>: <function escape_sequence at 0x7f84afc5be20>, <class 'dict'>: <function escape_dict at 0x7f84afc5bd80>, <class 'NoneType'>: <function escape_None at 0x7f84afc68400>, <class 'datetime.date'>: <function escape_date at 0x7f84afc68680>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f84afc685e0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f84afc684a0>, <class 'datetime.time'>: <function escape_time at 0x7f84afc68540>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f84b1550ef0>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f84b1550ef0>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14h\xad\x8d3q\x15\x9e\x1c\x9d\xcf[\x99\xe1L\xdc\xd2\xdd\x12y\x80_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0519413'
      authresp = b'h\xad\x8d3q\x15\x9e\x1c\x9d\xcf[\x99\xe1L\xdc\xd2\xdd\x12y\x80'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0519413'
      k = b'_pid'
      v = b'19413'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f84b1550ef0>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f84afb61f30>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f84afb61f30>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
Backup failed for Site doodle.test2. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['doodle.test', 'doodle.test2'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f84b0c4c5e0>
      exit_code = 1
      rollback_callback = None
      site = 'doodle.test2'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f84afca33d0>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f84afca33d0>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f84afb61f40>
      db_name = '_c50e25a1751d5327'
      user = '_c50e25a1751d5327'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f84afca33d0>
      site = 'doodle.test'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f84afb61f40>
  File "apps/frappe/frappe/database/mariadb/database.py", line 483, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84b1171df0>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f84afabdeb0>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_c50e25a1751d5327'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f84afb485e0>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f84afb48680>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84b1171df0>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_c50e25a1751d5327'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84b1171df0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84b1171df0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84b1171df0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f84b1171df0>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f84b0eee840>
      user = '_c50e25a1751d5327'
      password = ********
      host = '127.0.0.1'
      database = '_c50e25a1751d5327'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f84afc5bf60>, <class 'int'>: <function escape_int at 0x7f84afc68040>, <class 'float'>: <function escape_float at 0x7f84afc680e0>, <class 'str'>: <function escape_str at 0x7f84afc68360>, <class 'bytes'>: <function escape_bytes at 0x7f84afc682c0>, <class 'tuple'>: <function escape_sequence at 0x7f84afc5be20>, <class 'list'>: <function escape_sequence at 0x7f84afc5be20>, <class 'set'>: <function escape_sequence at 0x7f84afc5be20>, <class 'frozenset'>: <function escape_sequence at 0x7f84afc5be20>, <class 'dict'>: <function escape_dict at 0x7f84afc5bd80>, <class 'NoneType'>: <function escape_None at 0x7f84afc68400>, <class 'datetime.date'>: <function escape_date at 0x7f84afc68680>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f84afc685e0>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f84afc684a0>, <class 'datetime.time'>: <function escape_time at 0x7f84afc68540>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f84b0eee840>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f84b0eee840>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_c50e25a1751d5327\x00\x14c\xfc\xc8\xe1\xc2\xf9x\xe2\x8d\xf1\x8e\xe6\xa5\xed\x0e>\xe1\x0cc\x9a_c50e25a1751d5327\x00mysql_native_password\x006\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0519413'
      authresp = b'c\xfc\xc8\xe1\xc2\xf9x\xe2\x8d\xf1\x8e\xe6\xa5\xed\x0e>\xe1\x0cc\x9a'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x0519413'
      k = b'_pid'
      v = b'19413'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f84b0eee840>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\x15\x04#28000Access denied for user \'_c50e25a1751d5327\'@\'localhost\' (using password: YES)")
      packet_header = b'U\x00\x00\x02'
      btrl = 85
      btrh = 0
      packet_number = 2
      bytes_to_read = 85
      recv_data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f84afa281f0>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f84afa281f0>
      errno = 1045
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\x15\x04#28000Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errno = 1045
      errval = "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1045, "Access denied for user '_c50e25a1751d5327'@'localhost' (using password: YES)")
